import HealthyPy


    ##TODO
        # seperate out classes
        # WRITE COMMENTS
        # SORT DICTIONARIES AND LISTS
        # PUT A SPACE IN BETWEEN EACH NUTRIENT WHEN LISTING
        # ASK THE USER IF THEY WANT TO PRINT ANYTHING
        # FUNCTION TO CLEAR TABLES
        # LOOK INTO THE PROBLEM WITH AUTOMATICALLY ASSIGNING A FOODSEARCH TO A FOODID
        # IMPLEMENT A SEARCH FUNCTION

healthypy = HealthyPy.HealthyPy()
healthypy.Main()
